services:
  db:
    image: postgres:16
    container_name: epl_postgres
    environment:
      POSTGRES_DB: epl_dashboard
      POSTGRES_USER: epl_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - epl_pgdata:/var/lib/postgresql/data

volumes:
  epl_pgdata: